werweerw
  we
    r
      wer
        w
          ewe
            rw
              er
                we
                  r
                    w
                      er
                        w
                          erw
                            ;wer
                            wer;
                            for()
                              wer;
                              wer;
                            wer;
                            wer;w
                            wer;
                            wer;
                            wer;
                            wer;
                            qwe'q
                              ;we;q
                              ;e
                              ;q;we
                              ;q
                              ;
                              ;'qwe;qq;
                              ;e'q;';'qe;'
                              wq;';'
                              e;'
                              qw;'eq;'w
                              ;'e;q'
                              we;'
                              q;'w
                              e;'wewer
                              qw;'e;'q;'eq;'
                              we;'q;we;'
                              qw;';'
                              q;'eqw
                              e';q;'ew;qe
